-- Instructor MVC Project
-- Database name: online_quiz_platform
-- This project auto-creates the database and demo data through config/db.php.
-- Open http://localhost/instructor_mvc_full_project/login.php and the database will be prepared automatically.
